export enum OrderStatus {
  PENDING = 'PENDING',
  ASSIGNED = 'ASSIGNED',
  ACCEPTED = 'ACCEPTED',
  CREATED = 'CREATED',
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  EN_ROUTE_TO_PICKUP = 'EN_ROUTE_TO_PICKUP',
  ARRIVED_AT_PICKUP = 'ARRIVED_AT_PICKUP',
  PICKED_UP = 'PICKED_UP',
  STARTED = 'STARTED',
  EN_ROUTE_TO_DROPOFF = 'EN_ROUTE_TO_DROPOFF',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export enum OrderType {
  MOVE_TRANSPORT = 'MOVE_TRANSPORT',
  PARCEL_DELIVERY = 'PARCEL_DELIVERY',
  PASSENGER = 'PASSENGER',
  GOODS = 'GOODS',
}

export enum OrderEventType {
  CREATED = 'CREATED',
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  DRIVER_ACCEPTED = 'DRIVER_ACCEPTED',
  DRIVER_DECLINED = 'DRIVER_DECLINED',
  ARRIVED_AT_PICKUP = 'ARRIVED_AT_PICKUP',
  PICKED_UP = 'PICKED_UP',
  STARTED = 'STARTED',
  ARRIVED_AT_DROPOFF = 'ARRIVED_AT_DROPOFF',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  PAYMENT_INITIATED = 'PAYMENT_INITIATED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
}

export enum DiscountType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED = 'FIXED',
}
