export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  DRIVER = 'DRIVER',
  ADMIN = 'ADMIN',
  ADMIN_SUPERVISOR = 'ADMIN_SUPERVISOR',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum AdminRole {
  ADMIN = 'ADMIN',
  SUPERVISOR = 'SUPERVISOR',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}
